ServerPort: 8081
inventory_service_url: http://localhost:8082
payment_service_url: http://localhost:8083

Database:
  Host: localhost
  Port: "3306"
  User: root
  Password: root
  DBName: order_db
Redis:
  Addr: localhost:6379
  Password: ""
  DB: 0
MQ:
  Host: localhost
  Port: "5672"