ServerPort: 8081
InventoryServiceURL: http://localhost:8082
Database:
  Host: localhost
  Port: "3306"
  User: root
  Password: root
  DBName: order_db
Redis:
  Addr: localhost:6379
  Password: ""
  DB: 0
MQ:
  Host: localhost
  Port: "5672"